### ISSUE TITLE
Support static properties

### ISSUE THREAD

**Issue by erancahana** [tom-englert/Lazy.Fody#1]
Hi, first I wanted to thank you for picking up the mantle of supporting Lazy for Fody!
I wanted to inquire if you are planning to support Lazy for static properties.
Thanks!

**Comment by tom-englert** [comment]
No, I don't see any use case for this, since static properties are somewhat lazy by default.

**Comment by erancahana** [comment]
Ok ,thanks.
I was asking because I use Lazy.Fody instead of the AutoLazy project which is no longer supported.

I often used lazy on get only static properties in order to compute an immutable result once, and AutoLazy helped me clean up my code in that regard.
For example: 
`public static class BuildSettingsProvider {
	static readonly Lazy<IBuildSettings> _buildSettings = new Lazy<IBuildSettings>(() => new BuildSettings_Test());
	public static IBuildSettings BuildSettings => _buildSettings.Value;
}`

turned into:
`public static class BuildSettingsProvider {
	[Lazy] public static IBuildSettings BuildSettings => new BuildSettings_Test();
}`

which I thought was a lot more concise, readable and easier.
So I personally would like that option, unless I'm engaging in some anti-pattern that I'm not aware of.

Either way I wanted to thank you again for your work! Thanks!

**Comment by tom-englert** [comment]
But Lazy is redundant here, you can just write this:
```c#
public static class BuildSettingsProvider 
{ 
    public static readonly IBuildSettings BuildSettings = new BuildSettings_Test(); 
}
```

**Comment by erancahana** [comment]
I could, but many times I need to evaluate something more complicated than a simple assignment, that includes conditional branching, retry on fail policies, calling other initialization or setup code, etc...

In those situations I usually use the same traditional model as the "What gets compiled" section on the main project page (except the property and backing field are static), which is why I thought that the syntactic sugar that Lazy.Fody provides would perfectly fit that pattern as well.

**Comment by tom-englert** [comment]
Can you provide a PR with the adaptions?

**Comment by erancahana** [comment]
I can try, it might take me some time though as I'm in the middle of putting out several fires. I'm not very familiar with Fody add-in development but this may be a good opportunity to learn a bit more about the inner workings.

**Comment by erancahana** [comment]
i just saw that the pull request failed the automatic check, i think due to one of the FodyTools classes. I supplemented those from your master FodyTools on repo. 
i'll check again again.

**Comment by tom-englert** [comment]
looks like you updated FodyTools locally, but did not commit that..

**Comment by tom-englert** [comment]
@qwertio I fixed the problem with the tools, but your test does not compile for all frameworks. 
Maybe you just should do the test the same way as for the non-static properties,
