### ISSUE TITLE
Mark as development dependency

### ISSUE THREAD

**Issue by Tyrrrz** [tom-englert/Lazy.Fody#10]
Hi!

I've recently added this Fody plugin to a few of my projects, and it works great!

I did notice, however, that the package wasn't installed as a private dependency by default.

This could be fixed by adding this property to the corresponding `csproj` file:

```xml
<DevelopmentDependency>true</DevelopmentDependency>
```

**Comment by tom-englert** [comment]
Nope, that doesn't work: 4864a2fb6cfe082738cdf79fe420b853e59fa4d5

**Comment by Tyrrrz** [comment]
Can you please clarify what incompatible settings are you referring to? I set the refernce to `PrivateAssets="all"` and it works correctly.

**Comment by tom-englert** [comment]
DevelopmentDependency also sets the IncludeAssets, but without the compile part
https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
