### ISSUE TITLE
Lazy.Fody causes conflicts with Coverlet

### ISSUE THREAD

**Issue by Tyrrrz** [tom-englert/Lazy.Fody#11]
Hi!

It looks like introducing Lazy.Fody in my project broke Coverlet coverage collecting. Do you know if there's a way for me to fix it?

Here you can see a jump in coverage due to the report no longer including one of the projects:

![image](https://github.com/tom-englert/Lazy.Fody/assets/1935960/4f200da7-302f-40ef-a7ec-9cc8f1e6591e)

This is the last commit where the coverage worked correctly: https://github.com/Tyrrrz/YoutubeExplode/commit/754c1dac5968c63e76136d7743def99494c4e8b1

This is the commit that broke it: https://github.com/Tyrrrz/YoutubeExplode/commit/9d31e97efbb196bdba6da6b1757f8a01412800f5

To reproduce:

```console
git clone https://github.com/Tyrrrz/YoutubeExplode.git
git checkout 9d31e97efbb196bdba6da6b1757f8a01412800f5
dotnet test --collect:"XPlat Code Coverage"
```

Then navigate to `YoutubeExplode.Tests/TestResults/` and find that all coverage reports are empty.

**Comment by tom-englert** [comment]
Sorry, I'm not aware of coverlet implementation details, maybe better raise an issue at coverlet?

**Comment by Tyrrrz** [comment]
I imagine the issue arises from the fact that both sides try to rewrite the assembly for its own purposes.

Ironically, as I was about to raise an issue, I found a very similar one from myself a few years back: https://github.com/coverlet-coverage/coverlet/issues/1130

It looks like the problem only appears when `<DebugType>` is set to `embedded`, but it also seems to be a general Fody/Coverlet issue, not specific to Lazy.Fody. Going to close this issue.

**Comment by tom-englert** [comment]
Strange, I remember there was an issue with embedded pdbs in Cecil (https://github.com/jbevain/cecil/issues/856), but that has been fixed and both Fody and Coverlet seem to use the latest version of Cecil.

**Comment by Tyrrrz** [comment]
Can't really contribute more info on this, but removing `<DebugType>` did help. I'm now only setting it during `pack` so that the test stage is not affected.
