### ISSUE TITLE
Expression bodied member generates false positive CA1822

### ISSUE THREAD

**Issue by nitz** [tom-englert/Lazy.Fody#6]
First just want to say thank you for the fantastic weaver!

I've come across a code analysis false positive that's generated when a `Lazy` property has specific accessibility. I'm using `Lazy` for some internal properties that are then accessed and modified via other public properties in the class. The Roslyn analyzer generates a [CA1822](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822) for the internal expression bodied members, thinking that the member will create a new object on every access, and thus should be marked static.

Here's a small reproduction:

```csharp
using Lazy;

using System;

namespace ConsoleSandbox
{
    class Foo { public int Data { get; set; } }

    class Bar
    {
        [Lazy]
        internal Foo LazyFoo => new(); // CA1822

        public int Data
        {
            get => LazyFoo.Data;
            set => LazyFoo.Data = value;
        }
    }

    class Program
    {
        static void Main()
        {
            Bar b0 = new();
            Bar b1 = new();
            b0.Data = 4;
            b1.Data = 2;
            Console.WriteLine($"{b0.Data}{b1.Data}");
        }
    }
}

```

The output of the above is `42`.

Taking the CA1822's suggestion and marking the member as static, the output instead will be `22`, since both `b0` and `b1` are referencing the same Lazy-initialized `Foo`.

The workaround I've found for now seems to be to use a get-only autoproperty with an initializer:

```csharp
    // works correctly just doesn't look as nice!
    [Lazy]
    internal Foo LazyFoo { get; } = new();
```

This produces the correct result and doesn't generate the CA1822, as the CA realizes that each instance of `Bar` will have it's own single `LazyFoo`, rather than thinking `LazyFoo` always returns a new instance every time it's invoked.

I realize this whole issue might be a 'closedwontfix' case, as I'm not even sure how you'd be able to approach convincing the code analysis tool that you'll be weaving in data that absolutely does persist, but I thought it was enough of a 'gotcha' for me that it was worth letting you know.

Cheers!

**Comment by tom-englert** [comment]
The only solution I can think of is to add a suppression analyzer that suppresses CA1822 if the property has a lazy attribute.
If you think that's worth the effort, you could provide a PR for that.

**Comment by nitz** [comment]
You know, I actually started looking at creating my own little weaver this morning and have been tiptoeing into how to actually write proper IL for such things. Once I get my feet wet with my little project, I think I will circle back and give that a shot.

Thanks, Tom!

**Comment by tom-englert** [comment]
However Roslyn analyzers have nothing in common with IL weavers ...

**Comment by tom-englert** [comment]
@nitz can you try V1.10?

**Comment by nitz** [comment]
@tom-englert absolutely brilliant.

I really appreciate you putting in the effort. And as well I can learn a good bit from the way you implemented it (and your tests!)

It's not much but I sponsored you for a moment cause that's the closest I could get to buying you a beer.

Cheers!

**Comment by tom-englert** [comment]
Thanks alot 😄

To help making these tests standard you could up-vote https://github.com/dotnet/roslyn-sdk/issues/914
