### ISSUE TITLE
Expand LazyAttribute not working

### ISSUE THREAD

**Issue by ShoshanaTzi** [tom-englert/Lazy.Fody#8]
I want to use `LazyAttribute` with the property `LazyThreadSafetyMode` set to `ExecutionAndPublication`
But it's doesn't work
I guess it's depend on the FodyWeavers.xml
How can I do that?

My test code: 
```
public class LazyLoad : Lazy.LazyAttribute
    {
        public LazyLoad() : base(LazyThreadSafetyMode.ExecutionAndPublication)
        {

        }
    }
```

**Comment by tom-englert** [comment]
The readme shows how to correctly use it

**Comment by tom-englert** [comment]
You must use the Lazy attribute, you can't replace it by your own version
